import type { Metadata } from "next";
import { Geist, Geist_Mono, Lato } from "next/font/google"; // Import Lato
import "./globals.css";

// Initialize Geist Sans and Mono fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Initialize Lato font
const lato = Lato({
  variable: "--font-lato", // Add a CSS variable for Lato
  weight: ["400", "700"],  // You can customize the weights you want to use
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${lato.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
